apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: django-k8s
type: Opaque
stringData:
  postgres_db: main_db
  postgres_user: postgres_user
  postgres_password: postgres_password
  mysql_db: additional_db
  mysql_user: mysql_user
  mysql_password: mysql_password
  mysql_root_password: root_password